
spring:
  #配置druid数据源
  datasource:
    url: jdbc:mysql://219.146.150.102:12309/natergy?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=true
    username: root
    password: Nty-Mg-2018*04*09
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mvc:
    static-path-pattern=/static/**: #静态路径
    #视图定位jsp
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  resources:
    static-locations: classpath:/static/
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

server:
  servlet:
    context-path: /natergy-h5 #访问路径带项目名
    session:
      timeout: PT30M #session失效时间
  port: 8080

natergy:
  appId: wx3dabea702b3ea6cb
  appSecret: a7425fad59cf43f1d7e4a6b946e42033
  host: sungong1987.hk1.tunnelfrp.cc







